#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class BookDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBook(Book instance);
  partial void UpdateBook(Book instance);
  partial void DeleteBook(Book instance);
  partial void InsertOrder(Order instance);
  partial void UpdateOrder(Order instance);
  partial void DeleteOrder(Order instance);
  partial void InsertUser(User instance);
  partial void UpdateUser(User instance);
  partial void DeleteUser(User instance);
  #endregion
	
	public BookDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["connectionstring"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BookDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BookDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BookDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BookDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Book> Books
	{
		get
		{
			return this.GetTable<Book>();
		}
	}
	
	public System.Data.Linq.Table<OrderBook> OrderBooks
	{
		get
		{
			return this.GetTable<OrderBook>();
		}
	}
	
	public System.Data.Linq.Table<Order> Orders
	{
		get
		{
			return this.GetTable<Order>();
		}
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.books")]
public partial class Book : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Bookid;
	
	private string _Title;
	
	private string _Description;
	
	private string _Author;
	
	private System.Nullable<decimal> _Price;
	
	private System.Nullable<double> _Discount;
	
	private System.Nullable<int> _Nopages;
    private int nocopies;
    public int NoCopies
    {
        get
        {
            return nocopies;
        }
        set
        {
            nocopies = value;
        }
    }

    public decimal TotalNetPrice
    {
        get
        {
            return NoCopies * NetPrice;
        }
    }
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookidChanging(int value);
    partial void OnBookidChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDiscountChanging(System.Nullable<double> value);
    partial void OnDiscountChanged();
    partial void OnNopagesChanging(System.Nullable<int> value);
    partial void OnNopagesChanged();
    #endregion
	
	public Book()
	{
		OnCreated();
	}
	
    
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Bookid
	{
		get
		{
			return this._Bookid;
		}
		set
		{
			if ((this._Bookid != value))
			{
				this.OnBookidChanging(value);
				this.SendPropertyChanging();
				this._Bookid = value;
				this.SendPropertyChanged("Bookid");
				this.OnBookidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(200)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(100)")]
	public string Author
	{
		get
		{
			return this._Author;
		}
		set
		{
			if ((this._Author != value))
			{
				this.OnAuthorChanging(value);
				this.SendPropertyChanging();
				this._Author = value;
				this.SendPropertyChanged("Author");
				this.OnAuthorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Float")]
	public System.Nullable<double> Discount
	{
		get
		{
			return this._Discount;
		}
		set
		{
			if ((this._Discount != value))
			{
				this.OnDiscountChanging(value);
				this.SendPropertyChanging();
				this._Discount = value;
				this.SendPropertyChanged("Discount");
				this.OnDiscountChanged();
			}
		}
	}

    public decimal  NetPrice
    {
        get
        {
            decimal bookprice = Price.Value;
            return bookprice - (bookprice *  (decimal) Discount.Value  /  (decimal) 100);
        }
    }
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nopages", DbType="Int")]
	public System.Nullable<int> Nopages
	{
		get
		{
			return this._Nopages;
		}
		set
		{
			if ((this._Nopages != value))
			{
				this.OnNopagesChanging(value);
				this.SendPropertyChanging();
				this._Nopages = value;
				this.SendPropertyChanged("Nopages");
				this.OnNopagesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orderbooks")]
public partial class OrderBook
{
	
	private System.Nullable<int> _Orderid;
	
	private System.Nullable<int> _Bookid;
	
	private System.Nullable<int> _Nocopies;
	
	private System.Nullable<decimal> _NetPrice;
	
	public OrderBook()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orderid", DbType="Int", IsPrimaryKey = true)]
	public System.Nullable<int> Orderid
	{
		get
		{
			return this._Orderid;
		}
		set
		{
			if ((this._Orderid != value))
			{
				this._Orderid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bookid", DbType="Int", IsPrimaryKey = true )]
	public System.Nullable<int> Bookid
	{
		get
		{
			return this._Bookid;
		}
		set
		{
			if ((this._Bookid != value))
			{
				this._Bookid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nocopies", DbType="Int")]
	public System.Nullable<int> Nocopies
	{
		get
		{
			return this._Nocopies;
		}
		set
		{
			if ((this._Nocopies != value))
			{
				this._Nocopies = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetPrice", DbType="Money")]
	public System.Nullable<decimal> NetPrice
	{
		get
		{
			return this._NetPrice;
		}
		set
		{
			if ((this._NetPrice != value))
			{
				this._NetPrice = value;
			}
		}
	}


    private EntityRef<Book> _book;

    [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "order_book", Storage = "_book", ThisKey = "Bookid", OtherKey = "Bookid", IsForeignKey = true)]
    public Book Book
    {
        get
        {
            return this._book.Entity;
        }
        set
        {
                this._book.Entity = value;
        }
     }
 }

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orders")]
public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Orderid;
	
	private string _Email;
	
	private System.Nullable<System.DateTime> _OrderDate;
	
	private System.Nullable<char> _Status;
	
	private System.Nullable<System.DateTime> _Dispatchedon;
	
	private System.Nullable<System.DateTime> _Deliveredon;
	
	private string _ShippingAddress;
	
	private System.Nullable<decimal> _TotalAmount;
	
	private EntityRef<User> _User;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderidChanging(int value);
    partial void OnOrderidChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnOrderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderDateChanged();
    partial void OnStatusChanging(System.Nullable<char> value);
    partial void OnStatusChanged();
    partial void OnDispatchedonChanging(System.Nullable<System.DateTime> value);
    partial void OnDispatchedonChanged();
    partial void OnDeliveredonChanging(System.Nullable<System.DateTime> value);
    partial void OnDeliveredonChanged();
    partial void OnShippingAddressChanging(string value);
    partial void OnShippingAddressChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    #endregion
	
	public Order()
	{
		this._User = default(EntityRef<User>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orderid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Orderid
	{
		get
		{
			return this._Orderid;
		}
		set
		{
			if ((this._Orderid != value))
			{
				this.OnOrderidChanging(value);
				this.SendPropertyChanging();
				this._Orderid = value;
				this.SendPropertyChanged("Orderid");
				this.OnOrderidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				if (this._User.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> OrderDate
	{
		get
		{
			return this._OrderDate;
		}
		set
		{
			if ((this._OrderDate != value))
			{
				this.OnOrderDateChanging(value);
				this.SendPropertyChanging();
				this._OrderDate = value;
				this.SendPropertyChanged("OrderDate");
				this.OnOrderDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Char(1)")]
	public System.Nullable<char> Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dispatchedon", DbType="DateTime")]
	public System.Nullable<System.DateTime> Dispatchedon
	{
		get
		{
			return this._Dispatchedon;
		}
		set
		{
			if ((this._Dispatchedon != value))
			{
				this.OnDispatchedonChanging(value);
				this.SendPropertyChanging();
				this._Dispatchedon = value;
				this.SendPropertyChanged("Dispatchedon");
				this.OnDispatchedonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deliveredon", DbType="DateTime")]
	public System.Nullable<System.DateTime> Deliveredon
	{
		get
		{
			return this._Deliveredon;
		}
		set
		{
			if ((this._Deliveredon != value))
			{
				this.OnDeliveredonChanging(value);
				this.SendPropertyChanging();
				this._Deliveredon = value;
				this.SendPropertyChanged("Deliveredon");
				this.OnDeliveredonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingAddress", DbType="VarChar(300)")]
	public string ShippingAddress
	{
		get
		{
			return this._ShippingAddress;
		}
		set
		{
			if ((this._ShippingAddress != value))
			{
				this.OnShippingAddressChanging(value);
				this.SendPropertyChanging();
				this._ShippingAddress = value;
				this.SendPropertyChanged("ShippingAddress");
				this.OnShippingAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Money")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this.OnTotalAmountChanging(value);
				this.SendPropertyChanging();
				this._TotalAmount = value;
				this.SendPropertyChanged("TotalAmount");
				this.OnTotalAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_order", Storage="_User", ThisKey="Email", OtherKey="Email", IsForeignKey=true)]
	public User User
	{
		get
		{
			return this._User.Entity;
		}
		set
		{
			User previousValue = this._User.Entity;
			if (((previousValue != value) 
						|| (this._User.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._User.Entity = null;
					previousValue.Orders.Remove(this);
				}
				this._User.Entity = value;
				if ((value != null))
				{
					value.Orders.Add(this);
					this._Email = value.Email;
				}
				else
				{
					this._Email = default(string);
				}
				this.SendPropertyChanged("User");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Email;
	
	private string _Password;
	
	private string _Address;
	
	private string _Mobileno;
	
	private System.Nullable<System.DateTime> _Registeredon;
	
	private EntitySet<Order> _Orders;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnMobilenoChanging(string value);
    partial void OnMobilenoChanged();
    partial void OnRegisteredonChanging(System.Nullable<System.DateTime> value);
    partial void OnRegisteredonChanged();
    #endregion
	
	public User()
	{
		this._Orders = new EntitySet<Order>(new Action<Order>(this.attach_Orders), new Action<Order>(this.detach_Orders));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(300)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobileno", DbType="VarChar(30)")]
	public string Mobileno
	{
		get
		{
			return this._Mobileno;
		}
		set
		{
			if ((this._Mobileno != value))
			{
				this.OnMobilenoChanging(value);
				this.SendPropertyChanging();
				this._Mobileno = value;
				this.SendPropertyChanged("Mobileno");
				this.OnMobilenoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registeredon", DbType="DateTime")]
	public System.Nullable<System.DateTime> Registeredon
	{
		get
		{
			return this._Registeredon;
		}
		set
		{
			if ((this._Registeredon != value))
			{
				this.OnRegisteredonChanging(value);
				this.SendPropertyChanging();
				this._Registeredon = value;
				this.SendPropertyChanged("Registeredon");
				this.OnRegisteredonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_order", Storage="_Orders", ThisKey="Email", OtherKey="Email")]
	public EntitySet<Order> Orders
	{
		get
		{
			return this._Orders;
		}
		set
		{
			this._Orders.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.User = this;
	}
	
	private void detach_Orders(Order entity)
	{
		this.SendPropertyChanging();
		entity.User = null;
	}
}
#pragma warning restore 1591
