<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="BookDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="connectionstring" Provider="System.Data.SqlClient" />
  <Table Name="dbo.books" Member="Books">
    <Type Name="Book">
      <Column Name="Bookid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Nopages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="book_orderbook" Member="OrderBooks" ThisKey="Bookid" OtherKey="Bookid" Type="OrderBook" />
    </Type>
  </Table>
  <Table Name="dbo.orderbooks" Member="OrderBooks">
    <Type Name="OrderBook">
      <Column Name="Orderid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bookid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nocopies" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="book_orderbook" Member="Book" ThisKey="Bookid" OtherKey="Bookid" Type="Book" IsForeignKey="true" />
      <Association Name="order_orderbook" Member="Order" ThisKey="Orderid" OtherKey="Orderid" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orders" Member="Orders">
    <Type Name="Order">
      <Column Name="Orderid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Dispatchedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deliveredon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippingAddress" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="order_orderbook" Member="OrderBooks" ThisKey="Orderid" OtherKey="Orderid" Type="OrderBook" />
      <Association Name="user_order" Member="User" ThisKey="Email" OtherKey="Email" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="Users">
    <Type Name="User">
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Mobileno" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Registeredon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="user_order" Member="Orders" ThisKey="Email" OtherKey="Email" Type="Order" />
    </Type>
  </Table>
</Database>